--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lessons (id, uuid, name, img, length, level, premium, listening, "lessonText", likes, "fullText") FROM stdin;
1	1a4b9ed9-5f9b-498b-b113-4c62ff1b2df3	Introduction to Web Development	../../assets/images/webdev.webp	90	Beginner	f	t	Get started with web development in this comprehensive beginner's lesson. Learn HTML, CSS, and basic JavaScript to create your first web pages. By the end, you'll understand the structure of the web and be ready to pursue more advanced topics.	20	Introduction to Web Development is a comprehensive beginner's lesson where you'll delve into the basics of web development. This lesson is designed for those who are new to web development. You will learn about HTML, CSS, and basic JavaScript, which are the building blocks of the web. Through practical examples and hands-on exercises, you'll create your first web pages and gain a solid understanding of how web technologies work together. By the end of the lesson, you'll be equipped with the foundational knowledge needed to explore more advanced topics in web development.
4	95c8b63a-84ec-46d5-ba09-5bc88edf13f4	Advanced React Components	../../assets/images/webdev.webp	150	Advanced	t	f	Take your React skills to the next level with advanced component patterns and techniques. Learn about higher-order components, render props, and hooks to create reusable and composable UI elements. By mastering these concepts, you'll be able to build complex React applications with ease.	0	Advanced React Components is an advanced-level lesson designed to elevate your React skills. In this lesson, you'll explore advanced component patterns and techniques, including higher-order components, render props, and hooks. These concepts enable you to create reusable and composable UI elements, empowering you to build complex React applications with ease. Whether you're working on a large-scale project or aiming to deepen your understanding of React, this lesson provides invaluable insights into building robust and efficient applications.
6	999d2b0b-2d6d-4727-983a-59808094f181	Machine Learning Basics	../../assets/images/webdev.webp	120	Intermediate	f	f	Discover the fundamentals of machine learning in this introductory lesson. Learn about supervised and unsupervised learning, common algorithms like linear regression and k-means clustering, and practical applications of machine learning in various domains.	0	Machine Learning Basics is an intermediate-level lesson that provides an introduction to the fundamentals of machine learning. In this lesson, you'll learn about supervised and unsupervised learning, common algorithms such as linear regression and k-means clustering, and practical applications of machine learning in various domains. Whether you're a beginner exploring the field of machine learning or a practitioner looking to deepen your understanding, this lesson offers valuable insights into the core concepts and applications of machine learning.
8	8d6970f5-3c92-409e-8ac2-6ff5e68653ab	Ethical Hacking Fundamentals	../../assets/images/webdev.webp	120	Intermediate	f	t	Learn the basics of ethical hacking and penetration testing in this hands-on lesson. Explore common hacking techniques and vulnerabilities, such as SQL injection, cross-site scripting, and buffer overflows. By understanding how hackers operate, you'll be better equipped to defend against cyber attacks.	10	Ethical Hacking Fundamentals is an intermediate-level lesson that provides an introduction to the basics of ethical hacking and penetration testing. In this hands-on lesson, you'll explore common hacking techniques and vulnerabilities, including SQL injection, cross-site scripting, and buffer overflows. By understanding how hackers operate and exploit vulnerabilities, you'll gain valuable insights into defending against cyber attacks and securing your systems.
3	c299f84f-ee31-47f6-9025-bd48fdd7d9fc	Node.js fundamentals	../../assets/images/webdev.webp	90	Intermediate	f	f	Explore the basics of Node.js, a powerful runtime environment for server-side JavaScript. You'll learn how to set up a Node.js environment, handle HTTP requests, and build simple web servers. This lesson is perfect for front-end developers looking to expand their skill set.	68	Node.js Fundamentals is an intermediate-level lesson that introduces you to Node.js, a popular runtime environment for server-side JavaScript. In this lesson, you'll learn about setting up a Node.js environment, handling HTTP requests, and building basic web servers. Whether you're a front-end developer looking to expand your skill set or a newcomer to server-side programming, this lesson provides a solid foundation for working with Node.js.
10	c8c9c0f4-1d47-42c2-91d7-d24e207ecf8d	Android Development with Kotlin	../../assets/images/webdev.webp	150	Intermediate	t	f	Discover the Kotlin programming language and build Android apps from scratch. From setting up your development environment to designing user interfaces with XML and handling data with Room Persistence Library, this lesson covers all the essential skills for Android app development.	8	Android Development with Kotlin is an intermediate-level lesson that introduces you to building Android apps using Kotlin, a modern programming language. In this lesson, you'll discover the Kotlin programming language and learn how to build Android apps from scratch. You'll explore topics such as setting up your development environment, designing user interfaces with XML, and handling data with the Room Persistence Library. Whether you're new to Android development or looking to transition from Java to Kotlin, this lesson provides a comprehensive overview of essential skills for building Android apps.
7	a5d1487f-02fc-4823-b1ec-9f1b10d0165d	Python for Data Science	../../assets/images/webdev.webp	150	Intermediate	t	f	Explore the powerful libraries and tools available in Python for data science. From NumPy and Pandas for data manipulation to Matplotlib and Seaborn for visualization, this lesson covers everything you need to know to analyze and visualize data effectively.	26	Python for Data Science is an intermediate-level lesson that covers the essential libraries and tools for data analysis and visualization in Python. In this lesson, you'll explore libraries such as NumPy and Pandas for data manipulation and cleaning, Matplotlib and Seaborn for data visualization, and Scikit-learn for machine learning tasks. Whether you're a data scientist, analyst, or enthusiast, this lesson equips you with the skills needed to analyze and visualize data effectively using Python.
5	51dabb6c-7f60-4b94-a2a6-75b8bdf69db2	Data Structures and Algorithms	../../assets/images/webdev.webp	180	Intermediate	t	t	Gain a deeper understanding of fundamental data structures and algorithms in this intermediate-level lesson. Explore topics such as arrays, linked lists, trees, sorting algorithms, and searching algorithms. With practical examples and problem-solving exercises, you'll sharpen your problem-solving skills and become a more efficient programmer.	2	Data Structures and Algorithms is an intermediate-level lesson that delves into fundamental concepts in computer science. In this lesson, you'll explore various data structures and algorithms, including arrays, linked lists, trees, sorting algorithms, and searching algorithms. Through practical examples and problem-solving exercises, you'll gain a deeper understanding of these fundamental concepts and sharpen your problem-solving skills. Whether you're preparing for technical interviews or aiming to become a more efficient programmer, this lesson provides valuable insights into the world of data structures and algorithms.
15	34335a32-307d-486f-97b5-4287e71a18e2	Advanced SQL Queries	../../assets/images/webdev.webp	120	Advanced	t	f	Master the art of SQL querying with advanced techniques and optimizations. Learn about window functions, common table expressions, and indexing strategies to improve the performance and efficiency of your SQL queries.	54	Advanced SQL Queries is an advanced-level lesson that focuses on mastering the art of SQL querying. In this lesson, you'll learn advanced techniques and optimizations for writing efficient SQL queries. Topics covered include window functions, common table expressions, and indexing strategies. Whether you're a database administrator or developer, this lesson provides valuable insights into improving the performance and efficiency of your SQL queries.
11	d4215da9-06fc-4fa8-aedb-9d572c4c572b	Introduction to Cybersecurity	../../assets/images/webdev.webp	90	Beginner	f	f	Get an overview of cybersecurity concepts and principles in this beginner-friendly lesson. Learn about common threats and attacks, such as malware, phishing, and social engineering, and explore strategies for protecting against them.	42	Introduction to Cybersecurity is a beginner-friendly lesson that provides an overview of cybersecurity concepts and principles. In this lesson, you'll learn about common threats and attacks, such as malware, phishing, and social engineering, and explore strategies for protecting against them. Whether you're new to cybersecurity or looking to enhance your knowledge, this lesson offers valuable insights into the importance of cybersecurity and how to safeguard against cyber threats.
13	13a82d06-3f57-46ec-86c3-29095349e9cb	Game Development with Unity	../../assets/images/webdev.webp	180	Intermediate	t	f	Create your own games with Unity, the popular game development platform. From designing levels and characters to implementing gameplay mechanics and adding sound effects, this lesson covers all the essential aspects of game development.	6	Game Development with Unity is an intermediate-level lesson that introduces you to creating games with Unity, a popular game development platform. In this lesson, you'll learn about designing levels and characters, implementing gameplay mechanics, and adding sound effects. Whether you're a hobbyist or aspiring game developer, this lesson provides a comprehensive overview of the essential aspects of game development using Unity.
16	a6f6715a-cdbf-4b4c-8ccf-19852e272ad4	Digital Marketing Fundamentals	../../assets/images/webdev.webp	90	Beginner	f	f	Gain a foundational understanding of digital marketing concepts and strategies in this beginner's lesson. Learn about SEO, social media marketing, email marketing, and other essential techniques for promoting products and services online.	16	Digital Marketing Fundamentals is a beginner's lesson that provides a foundational understanding of digital marketing concepts and strategies. In this lesson, you'll learn about SEO, social media marketing, email marketing, and other essential techniques for promoting products and services online. Whether you're new to digital marketing or looking to enhance your skills, this lesson offers valuable insights into the fundamentals of digital marketing and how to effectively promote products and services online.
9	3f6e97f8-f1f2-4fc0-b890-c7f9d7a86d71	iOS App Development with Swift	../../assets/images/webdev.webp	180	Intermediate	t	f	Dive into iOS app development using Swift, Apple's powerful programming language. Learn how to build user interfaces, handle user input, and connect to web services using UIKit and Alamofire. By the end of this lesson, you'll have the skills to create your own iOS apps and publish them on the App Store.	20	iOS App Development with Swift is an intermediate-level lesson that introduces you to iOS app development using Swift, Apple's powerful programming language. In this lesson, you'll learn how to build user interfaces, handle user input, and connect to web services using UIKit and Alamofire. By the end of this lesson, you'll have the skills and knowledge needed to create your own iOS apps and publish them on the App Store, whether you're a beginner exploring app development or an experienced developer looking to expand your skill set.
12	d6a5e8cb-d8e7-42ef-95d0-277bb7ff9e58	Artificial Intelligence Fundamentals	../../assets/images/webdev.webp	120	Intermediate	f	f	Explore the basics of artificial intelligence and machine learning in this intermediate-level lesson. Learn about neural networks, deep learning, and natural language processing, and discover how AI is revolutionizing industries such as healthcare, finance, and transportation.	26	Artificial Intelligence Fundamentals is an intermediate-level lesson that provides an introduction to the basics of artificial intelligence and machine learning. In this lesson, you'll learn about neural networks, deep learning, and natural language processing, and discover how AI is revolutionizing industries such as healthcare, finance, and transportation. Whether you're new to AI or looking to deepen your understanding, this lesson offers valuable insights into the core concepts and applications of artificial intelligence.
2	3b754d82-5722-4d1d-87f4-12db7dd9b3cc	Responsive Web Design	../../assets/images/webdev.webp	120	Intermediate	t	f	Learn how to create responsive websites that adapt to different screen sizes and devices. This lesson covers CSS media queries, flexible layouts, and best practices for designing websites that look great on desktops, tablets, and smartphones.	6	Responsive Web Design is an intermediate-level lesson that focuses on creating websites that adapt to various screen sizes and devices. You'll explore CSS media queries, which allow you to apply different styles based on device characteristics. Additionally, you'll learn about flexible layouts and best practices for designing responsive websites that provide optimal user experiences across desktops, tablets, and smartphones. By mastering these techniques, you'll be able to create visually appealing and functional websites that cater to a wide range of users.
14	b802f5cc-0d40-4f62-b4de-4729e15c0b0f	Blockchain Basics	../../assets/images/webdev.webp	90	Beginner	f	f	Discover the fundamentals of blockchain technology in this beginner-friendly lesson. Learn how blockchain works, its applications beyond cryptocurrency, and the potential impact it could have on various industries.	16	Blockchain Basics is a beginner-friendly lesson that provides an introduction to the fundamentals of blockchain technology. In this lesson, you'll learn about how blockchain works, its applications beyond cryptocurrency, and the potential impact it could have on various industries. Whether you're new to blockchain or looking to deepen your understanding, this lesson offers valuable insights into the core concepts and potential applications of blockchain technology.
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, firstname, lastname, emailadress, phonenumber, premiumuser) FROM stdin;
1	johndoe	raspb€rrY_314	John	Doe	john@doe.com	+421859758965	t
2	buster28	m00n&b4ck	Buster	Moon	moon@busty.net	+420257846846	f
\.


--
-- PostgreSQL database dump complete
--

